service_now:
  instance_name: "<instance name>"
  user_name: "<user>"
  password: "<password>"

workflow:
  # Name of an existing ServiceNow table field that will be used as a key to uniquely reference an alert group in incident management workflow
  incident_group_key_field: "<incident table field>"
  # ID if the incident states for which existing incident will not be updated on firing alert group; leading to the creation of a new incident
  no_update_states: [6,7]

default_incident:
  # Sysid or name of the assignment group
  assignment_group: "<assignment group>"
  # Impact: Business loss and potential damage (for example, financial, customer, regulation, security, reputation, brand) caused by the incident
  # Common values: 1 (High), 2 (Medium), 3 (Low)
  impact: 2
  # Urgency: Speed at which the business expects the incident to be resolved
  # Common values: 1 (High), 2 (Medium), 3 (Low)
  urgency: 2
  # Name of the company
  company: "<company name>"
  # Contact type of the incident
  contact_type : "<contact type>"