service_now:
  instance_name: "<instance name>"
  user_name: "<user>"
  password: "<password>"

default_incident:
  # Sysid or name of the assignment group
  assignment_group: "<assignment group>"
  # Impact: Business loss and potential damage (for example, financial, customer, regulation, security, reputation, brand) caused by the incident
  # Common values: 1 (High), 2 (Medium), 3 (Low)
  impact: 2
  # Urgency: Speed at which the business expects the incident to be resolved
  # Common values: 1 (High), 2 (Medium), 3 (Low)
  urgency: 2